BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Migrations;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.Models;
using BulkyBook.Models.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Stripe;
using System.Data;
using Product = BulkyBook.Models.Product;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> ProductList = _unitOfWork._productRepository.GetAll(includeProperties:"Category").ToList();
          

            return View(ProductList);
        }

        public IActionResult Upsert(int? id)
        {
           
           // ViewData["CategoryList"] = CategoryList;
            ProductVM productVM = new ProductVM()
            {
                CategoryList = _unitOfWork._categoryRepository.GetAll().
                 Select(u => new SelectListItem
                 {
                     Text = u.Name,
                     Value = u.CategoryId.ToString(),
                 }),
            Product = new Product()
            };
            if(id == null|| id==0) {
                return View(productVM);
            }
            else
            {
                productVM.Product=_unitOfWork._productRepository.Get(u=>u.Id==id,includeProperties:"ProductImages");
                return View(productVM);
            }
            
        }

        [HttpPost]
        public IActionResult Upsert( ProductVM productVM,List<IFormFile> files)
        {

            if (ModelState.IsValid)
            {
				if (productVM.Product.Id == 0)
				{
					_unitOfWork._productRepository.Add(productVM.Product);
				}
				else
				{
					_unitOfWork._productRepository.update(productVM.Product);
					TempData["success"] = "Product Updated Succesfully";
				}

				_unitOfWork.Save();
				string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string productPath = @"images\products\product-" + productVM.Product.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);
                        if (!Directory.Exists(finalPath))
                        {
                            Directory.CreateDirectory(finalPath);
                        }
                        using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        ProductImage productImage = new()
                        {
                            ImageUrl = @"\" + productPath + @"\" + fileName,
                            ProductId = productVM.Product.Id,
                        };

                       if (productVM.Product.ProductImages == null)
                        {
							productVM.Product.ProductImages=new List<ProductImage>();

						}
						productVM.Product.ProductImages.Add(productImage);

					}
                    _unitOfWork._productRepository.update(productVM.Product);
                    _unitOfWork.Save();
                }
              
              
               
                TempData["success"] = "Product created/updated Succesfully";
                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork._categoryRepository.GetAll().
                 Select(u => new SelectListItem
                 {
                     Text = u.Name,
                     Value = u.CategoryId.ToString(),
                 });
                return View(productVM);
            }
            
        }
          

        public IActionResult DeleteImage(int ImageId)
        {
            var imageToBeDeleted = _unitOfWork._productImageRepository.Get(u => u.Id == ImageId);
          int productId= imageToBeDeleted.ProductId;
            if(imageToBeDeleted != null)
            {
                if (!string.IsNullOrEmpty(imageToBeDeleted.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, imageToBeDeleted.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                _unitOfWork._productImageRepository.Remove(imageToBeDeleted);
                _unitOfWork.Save();

                TempData["success"] = "Deleted succesfully";

            }
            return RedirectToAction(nameof(Upsert), new {id=productId});
        }

       

     


        

        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            List<BulkyBook.Models.Product> objProductList = _unitOfWork._productRepository.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProductList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork._productRepository.Get(u=>u.Id==id);
           if(productToBeDeleted == null)
            {
                return Json(new {success=false,Message="Error while deleting"});
            }

           

        
            string productPath = @"images\products\product-" + id;
            string finalPath = Path.Combine(_webHostEnvironment.WebRootPath, productPath);
            if (!Directory.Exists(finalPath))
            {
                string[] filePaths=Directory.GetFiles(finalPath);
                foreach (string filePath in filePaths)
                {
                    System.IO.File.Delete(filePath);
                }
                Directory.Delete(finalPath);
            }

            _unitOfWork._productRepository.Remove(productToBeDeleted);
            _unitOfWork.Save();
            
            return Json(new { success=true,Message="Delete Successful" });
        }
        #endregion
    }
}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.Models;
using BulkyBook.Models.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
		private readonly UserManager<IdentityUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            
			_userManager= userManager;
            _roleManager = roleManager;
            _unitOfWork = unitOfWork;


        }
        public IActionResult Index()
        {
            return View();
        }

		public IActionResult RoleManagement(string userId)
		{
            
			RoleManagementVM RoleVM = new RoleManagementVM()
            {
                ApplicationUser= _unitOfWork._applicationUserRepository.Get(u=>u.Id==userId,includeProperties:"Company"),
                RoleList=_roleManager.Roles.Select(i=>new SelectListItem
                {
                    Text=i.Name,
                    Value=i.Name
                }),
				CompanyList = _unitOfWork._companyRepository.GetAll().Select(i => new SelectListItem
				{
					Text = i.Name,
					Value = i.Id.ToString()
				})
			};
            RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork._applicationUserRepository.Get(u => u.Id == userId))
                .GetAwaiter().GetResult().FirstOrDefault();
			return View(RoleVM);
		}

		public IActionResult RoleManagement(RoleManagementVM roleManagementVM)
		{
         
            string oldRole = _userManager.GetRolesAsync(_unitOfWork._applicationUserRepository.Get(u => u.Id == roleManagementVM.ApplicationUser.Id))
                .GetAwaiter().GetResult().FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork._applicationUserRepository.Get(u => u.Id == roleManagementVM.ApplicationUser.Id);
            if (!(roleManagementVM.ApplicationUser.Role == oldRole))
            {
                // a role was updated
               

				if (roleManagementVM.ApplicationUser.Role==SD.Role_Company) {
                    applicationUser.CompanyId = roleManagementVM.ApplicationUser.CompanyId;
                }
                if (oldRole == SD.Role_Company)
                {
                    applicationUser.CompanyId = null;

                }
                _unitOfWork._applicationUserRepository.Update(applicationUser);
                _unitOfWork.Save();
                _userManager.RemoveFromRoleAsync(applicationUser,oldRole).GetAwaiter().GetResult();
				_userManager.AddToRoleAsync(applicationUser,roleManagementVM.ApplicationUser.Role).GetAwaiter().GetResult();
			}
            else
            {
                if(oldRole == SD.Role_Company && applicationUser.CompanyId!=roleManagementVM.ApplicationUser.CompanyId) {
                  applicationUser.CompanyId=roleManagementVM.ApplicationUser.CompanyId;
                    _unitOfWork._applicationUserRepository.Update(applicationUser);
                    _unitOfWork.Save();
                }
            }
            return RedirectToAction("Index");
		}



		#region
		[HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objUserList = _unitOfWork._applicationUserRepository.GetAll(includeProperties:"Company").ToList();
           

          foreach (var user in objUserList) {

                user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();


			if (user.Company==null)
                {
                    user.Company = new Company() { Name=""};
                }
            
            }
            
            
            return Json(new { data = objUserList });
        }

        [HttpDelete]
        public IActionResult LockUnlock([FromBody] string id)
        {
           var objFromDb=_unitOfWork._applicationUserRepository.Get(u=>u.Id== id);
            if (objFromDb==null)
            {
                return Json(new { success = false, Message = "Error while locking unlocking" });
                
            }
            if(objFromDb.LockoutEnd!=null && objFromDb.LockoutEnd > DateTime.Now)
            {
				//user is currently locked and we need to unlock them
				objFromDb.LockoutEnd=DateTime.Now;
			}
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);

			}
            _unitOfWork._applicationUserRepository.Update(objFromDb);
            _unitOfWork.Save();

            return Json(new { success = false, Message = "Deleted Successfully" });
        }
        #endregion







       
    }
}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BulkyBookWeb.ViewComponents
{
	public class ShoppingCartViewComponent : ViewComponent
	{
		private readonly IUnitOfWork _unitOfWork;
		public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
				{
					return View(HttpContext.Session.GetInt32(SD.SessionCart));
				}
				else
				{
					HttpContext.Session.SetInt32(SD.SessionCart,
						_unitOfWork._shoppingCartRepository.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
					return View(HttpContext.Session.GetInt32(SD.SessionCart));
				}
			}
			else
			{
				HttpContext.Session.Clear();
				return View(0);
			}
		}
	}
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor IHttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
  
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"/>
</head>
<body>

	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" href="#"><img src="/images/book.png"</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor02">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">

							<a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						
						@if (User.IsInRole(SD.Role_Admin))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
								<div class="dropdown-menu">
									<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
									<a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
									<a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
									<a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
								</div>
							</li>
						}
						<li class="nav-item">
							<a class=nav-link asp-area="Admin" asp-controller="Order" asp-action="Index">
								Manage Order
							</a>
						</li>

						
					
						
							<li class="nav-item">
								<a class=nav-link asp-area="Customer" asp-controller="Cart" asp-action="Index">
									@await Component.InvokeAsync("ShoppingCart")
									
								</a>
							</li>
						

					</ul>
					<partial name="_LoginPartial" />
					 <form class="d-flex">
					<input class="form-control me-sm-2" type="text" placeholder="Search">
					<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
					</form>
				</div>
			</div>
		</nav>

	</header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-center">
          Made with  <i class="bi bi-heart-fill"></i> by me
        </div>
    </footer>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/2t30t7cqwos2k903hgj8jq4nujq0h7qkp10derpzx921jonx/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" /></script>
   <script type="text/javascript">
        toastr.success('@TempData["success"]');
   </script>
   
}


@if (TempData["error"] != null) 
{
       <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" />
        </script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>

}